skills_amazon = [
    {"name": "Jab", "i": 0},
    {"name": "Power Strike", "i": 1},
    {"name": "Poison Javelin", "i": 2},
    {"name": "Fend", "i": 3},
    {"name": "Lightning Bolt", "i": 4},
    {"name": "Charged Strike", "i": 5},
    {"name": "Plague Javelin", "i": 6},
    {"name": "Molten Strike", "i": 7},
    {"name": "Lightning Strike", "i": 8},
    {"name": "Lightning Fury", "i": 9},
    {"name": "Inner Sight", "i": 10},
    {"name": "Lethal Strike", "i": 11},
    {"name": "Phase Run", "i": 12},
    {"name": "Dodge", "i": 13},
    {"name": "Avoid", "i": 14},
    {"name": "Penetrate", "i": 15},
    {"name": "Evade", "i": 16},
    {"name": "Decoy", "i": 17},
    {"name": "Valkyrie", "i": 18},
    {"name": "Pierce", "i": 19},
    {"name": "Cold Arrow", "i": 20},
    {"name": "Magic Arrow", "i": 21},
    {"name": "Multiple Shot", "i": 22},
    {"name": "Fire Arrow", "i": 23},
    {"name": "Ice Arrow", "i": 24},
    {"name": "Guided Arrow", "i": 25},
    {"name": "Exploding Arrow", "i": 26},
    {"name": "Strafe", "i": 27},
    {"name": "Immolation Arrow", "i": 28},
    {"name": "Freezing Arrow", "i": 29},
]
skills_assassin = [
    {"name": "Dragon Claw", "i":0},
    {"name": "Fists of Fire", "i":1},
    {"name": "Claws of Thunder", "i":2},
    {"name": "Blades of Ice", "i":3},
    {"name": "Tiger Strike", "i":4},
    {"name": "Dragon Talon", "i":5},
    {"name": "Cobra Strike", "i":6},
    {"name": "Dragon Flight", "i":7},
    {"name": "Claw Mastery", "i":9},
    {"name": "Psychic Hammer", "i":10},
    {"name": "Burst of Speed", "i":11},
    {"name": "Weapon Block", "i":13},
    {"name": "Cloak of Shadows", "i":14},
    {"name": "Fade", "i":15},
    {"name": "Shadow Warrior", "i":16},
    {"name": "Mind Blast", "i":17},
    {"name": "Venom", "i":18},
    {"name": "Shadow Master", "i":19},
    {"name": "Fire Blast", "i":20},
    {"name": "Shock Web", "i":21},
    {"name": "Blade Throw", "i":22},
    {"name": "Charged Bolt Sentry", "i":23},
    {"name": "Wake of Fire", "i":24},
    {"name": "Blade Fury", "i":25},
    {"name": "Lightning Sentry", "i":26},
    {"name": "Wake of Inferno", "i":27},
    {"name": "Death Sentry", "i":28},
    {"name": "Blade Shield", "i":29}
]
skills_barbarian = [
    {"name": "Howl", "i":0},
    {"name": "Find Potion", "i":1},
    {"name": "Taunt", "i":2},
    {"name": "Shout", "i":3},
    {"name": "Find Item", "i":4},
    {"name": "Battle Cry", "i":5},
    {"name": "Battle Orders", "i":6},
    {"name": "Grim Ward", "i":7},
    {"name": "War Cry", "i":8},
    {"name": "Battle Command", "i":9},
    {"name": "Edged Weapon Mastery", "i":10},
    {"name": "Pole Weapon Mastery", "i":11},
    {"name": "Blunt Weapon Mastery", "i":12},
    {"name": "Thrown Weapon Mastery", "i":13},
    {"name": "Increased Stamina", "i":14},
    {"name": "Counter Attack", "i":15},
    {"name": "Iron Skin", "i":16},
    {"name": "Increased Speed", "i":17},
    {"name": "Puncture", "i":18},
    {"name": "Whirling Axes", "i":19},
    {"name": "Natural Resistance", "i":20},
    {"name": "Double Swing", "i":21},
    {"name": "Frenzy", "i":22},
    {"name": "Bash", "i":23},
    {"name": "Cleave", "i":24},
    {"name": "Stun", "i":25},
    {"name": "Leap Slam", "i":26},
    {"name": "Double Throw", "i":27},
    {"name": "Concentrate", "i":28},
    {"name": "Ethereal Throw", "i":29},
    {"name": "Whirlwind", "i":30},
];
skills_druid = [
    {"name": "Firestorm", "i":0},
    {"name": "Molten Boulder", "i":1},
    {"name": "Flame Dash", "i":2},
    {"name": "Arctic Blast", "i":3},
    {"name": "Fissure", "i":4},
    {"name": "Cyclone Armor", "i":5},
    {"name": "Twister", "i":6},
    {"name": "Volcano", "i":7},
    {"name": "Tornado", "i":8},
    {"name": "Armageddon", "i":9},
    {"name": "Hurricane", "i":10},
    {"name": "Werewolf", "i":11},
    {"name": "Lycanthropy", "i":12},
    {"name": "Werebear", "i":13},
    {"name": "Feral Rage", "i":14},
    {"name": "Maul", "i":15},
    {"name": "Rabies", "i":16},
    {"name": "Fire Claws", "i":17},
    {"name": "Hunger", "i":18},
    {"name": "Shock Wave", "i":19},
    {"name": "Fury", "i":20},
    {"name": "Raven", "i":21},
    {"name": "Poison Creeper", "i":22},
    {"name": "Heart of Wolverine", "i":23},
    {"name": "Summon Spirit Wolf", "i":24},
    {"name": "Carrion Vine", "i":25},
    {"name": "Oak Sage", "i":26},
    {"name": "Summon Dire Wolf", "i":27},
    {"name": "Solar Creeper", "i":28},
    {"name": "Spirit of Barbs", "i":29},
];
skills_necromancer = [
    {"name": "Summon Mastery", "i":0},
    {"name": "Raise Skeleton Warrior", "i":1},
    {"name": "Bone Offering", "i":2},
    {"name": "Clay Golem", "i":3},
    {"name": "Flesh Offering", "i":4},
    {"name": "Raise Skeletal Mage", "i":5},
    {"name": "Blood Golem", "i":6},
    {"name": "Convocation", "i":7},
    {"name": "Iron Golem", "i":8},
    {"name": "Fire Golem", "i":9},
    {"name": "Revive", "i":10},
    {"name": "Deadly Poison", "i":11},
    {"name": "Teeth", "i":12},
    {"name": "Bone Armor", "i":13},
    {"name": "Corpse Explosion", "i":14},
    {"name": "Desecrate", "i":15},
    {"name": "Bone Spear", "i":16},
    {"name": "Bone Wall", "i":17},
    {"name": "Bone Spirit", "i":18},
    {"name": "Poison Nova", "i":19},
    {"name": "Amplify Damage", "i":20},
    {"name": "Dim Vision", "i":21},
    {"name": "Hemorrhage", "i":22},
    {"name": "Weaken", "i":23},
    {"name": "Iron Maiden", "i":24},
    {"name": "Terror", "i":25},
    {"name": "Confuse", "i":26},
    {"name": "Life Tap", "i":27},
    {"name": "Attract", "i":28},
    {"name": "Decrepify", "i":29},
    {"name": "Lower Resist", "i":30},
];
skills_paladin = [
    {"name": "Prayer", "i":0},
    {"name": "Resist Fire", "i":1},
    {"name": "Defiance", "i":2},
    {"name": "Resist Cold", "i":3},
    {"name": "Cleansing", "i":4},
    {"name": "Resist Lightning", "i":5},
    {"name": "Vigor", "i":6},
    {"name": "Meditation", "i":7},
    {"name": "Redemption", "i":8},
    {"name": "Salvation", "i":9},
    {"name": "Might", "i":10},
    {"name": "Holy Fire", "i":11},
    {"name": "Precision", "i":12},
    {"name": "Blessed Aim", "i":13},
    {"name": "Concentration", "i":14},
    {"name": "Holy Freeze", "i":15},
    {"name": "Holy Shock", "i":16},
    {"name": "Sanctuary", "i":17},
    {"name": "Fanaticism", "i":18},
    {"name": "Conviction", "i":19},
    {"name": "Sacrifice", "i":20},
    {"name": "Smite", "i":21},
    {"name": "Holy Bolt", "i":22},
    {"name": "Zeal", "i":23},
    {"name": "Charge", "i":24},
    {"name": "Vengeance", "i":25},
    {"name": "Blessed Hammer", "i":26},
    {"name": "Conversion", "i":27},
    {"name": "Holy Shield", "i":28},
    {"name": "Fist of the Heavens", "i":29},
    {"name": "Dashing Strike", "i":30},
];
skills_sorceress = [
    {"name": "Ice Bolt", "i":0},
    {"name": "Frigerate", "i":1},
    {"name": "Frost Nova", "i":2},
    {"name": "Ice Blast", "i":3},
    {"name": "Shiver Armor", "i":4},
    {"name": "Glacial Spike", "i":5},
    {"name": "Blizzard", "i":6},
    {"name": "Freezing Pulse", "i":7},
    {"name": "Chilling Armor", "i":8},
    {"name": "Frozen Orb", "i":9},
    {"name": "Cold Mastery", "i":10},
    {"name": "Charged Bolt", "i":11},
    {"name": "Static Field", "i":12},
    {"name": "Telekinesis", "i":13},
    {"name": "Nova", "i":14},
    {"name": "Lightning Surge", "i":15},
    {"name": "Chain Lightning", "i":16},
    {"name": "Teleport", "i":17},
    {"name": "Discharge", "i":18},
    {"name": "Energy Shield", "i":19},
    {"name": "Lightning Mastery", "i":20},
    {"name": "Thunder Storm", "i":21},
    {"name": "Fire Bolt", "i":22},
    {"name": "Warmth", "i":23},
    {"name": "Inferno", "i":24},
    {"name": "Immolate", "i":25},
    {"name": "Fire Ball", "i":26},
    {"name": "Fire Wall", "i":27},
    {"name": "Enflame", "i":28},
    {"name": "Meteor", "i":29},
    {"name": "Fire Mastery", "i":30},
    {"name": "Hydra", "i":31},
];